
version: '3'

services:
  postgres:
    image: postgres:14.5
    command: postgres -c 'max_connections=250'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  api:
    image: api
    depends_on:
      - postgres
    ports:
      - ${API_PORT}:7085
    environment:
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      REDIRECT_AFTER_LOGIN: ${REDIRECT_AFTER_LOGIN}
    volumes:
      - postgres-data:/var/lib/api

  client:
    image: client
    environment:
      NUXT_PUBLIC_API_BASE: ${NUXT_PUBLIC_API_BASE}
      NUXT_PUBLIC_GITHUB_CLIENT_ID: ${NUXT_PUBLIC_GITHUB_CLIENT_ID}
    ports:
      - 8080:3000
    depends_on:
      - api
      
volumes:
  postgres-data:

